### ISSUE TITLE
How to run ant?

### ISSUE THREAD

**Issue by romanr** [frekele/docker-ant#44]
The ant command is not available in path or calling directly,

> /opt/ant/bin/ant: No such file or directory

**Comment by frekele** [comment]
Hi @romanr 

You can run it in several ways.

#### Default option (with s6-overlay):
You must create an init script so that service.d automatically runs in deploy.
create a file /etc/services.d/ant/run
```
#!/usr/bin/with-contenv sh

#Run with user root pid 1.
exec ant -f my-build.xml;

#Or run with myuser.
#exec s6-setuidgid myuser ant -f my-build.xml;
```

Create a Dockerfile and Extend frekele/ant:(tag-version)
```
FROM frekele/ant:1.10.1-jdk8

# copy your custom run to /etc/services.d/ant/run
COPY my-run /etc/services.d/ant/run
```

#### Another option is to use after deployment, inside the container simply by running:
```
ant -f my-build.xml;
```
#### Or send the command via arguments:
```
docker run --rm --name my-docker-ant frekele/ant:1.10.1-jdk8   ant -f my-build.xml
```

you do not need to enter the complete installation path '/opt/ant/bin/ant/'  simply use 'ant' executable.

Even if you use '/opt/ant/bin/ant/', it should work, maybe the image you use is broken.

What image are you using?

Hope this helps.

**Comment by romanr** [comment]
My question is that “ant” command is not found when it’s called. Just manually called.

**Comment by frekele** [comment]
It should work.

**Comment by kucerarichard** [comment]
Thanks this explanation seems to help.
